// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchain_security/ccv/consumer/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryCurrentProviderHoldingPoolRequest struct {
}

func (m *QueryCurrentProviderHoldingPoolRequest) Reset() {
	*m = QueryCurrentProviderHoldingPoolRequest{}
}
func (m *QueryCurrentProviderHoldingPoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentProviderHoldingPoolRequest) ProtoMessage()    {}
func (*QueryCurrentProviderHoldingPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f627751d3cc10225, []int{0}
}
func (m *QueryCurrentProviderHoldingPoolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentProviderHoldingPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentProviderHoldingPoolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentProviderHoldingPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentProviderHoldingPoolRequest.Merge(m, src)
}
func (m *QueryCurrentProviderHoldingPoolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentProviderHoldingPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentProviderHoldingPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentProviderHoldingPoolRequest proto.InternalMessageInfo

type CurrentProviderHoldingPool struct {
	ValidatorWeights []*ValidatorWeight                       `protobuf:"bytes,1,rep,name=validator_weights,json=validatorWeights,proto3" json:"validator_weights,omitempty"`
	StartHeight      int64                                    `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	CurrentHeight    int64                                    `protobuf:"varint,3,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	Tokens           github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=tokens,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"tokens" yaml:"tokens"`
}

func (m *CurrentProviderHoldingPool) Reset()         { *m = CurrentProviderHoldingPool{} }
func (m *CurrentProviderHoldingPool) String() string { return proto.CompactTextString(m) }
func (*CurrentProviderHoldingPool) ProtoMessage()    {}
func (*CurrentProviderHoldingPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_f627751d3cc10225, []int{1}
}
func (m *CurrentProviderHoldingPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentProviderHoldingPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentProviderHoldingPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentProviderHoldingPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentProviderHoldingPool.Merge(m, src)
}
func (m *CurrentProviderHoldingPool) XXX_Size() int {
	return m.Size()
}
func (m *CurrentProviderHoldingPool) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentProviderHoldingPool.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentProviderHoldingPool proto.InternalMessageInfo

func (m *CurrentProviderHoldingPool) GetValidatorWeights() []*ValidatorWeight {
	if m != nil {
		return m.ValidatorWeights
	}
	return nil
}

func (m *CurrentProviderHoldingPool) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *CurrentProviderHoldingPool) GetCurrentHeight() int64 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

func (m *CurrentProviderHoldingPool) GetTokens() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type ValidatorWeight struct {
	Address string                                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight  github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=weight,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"weight"`
}

func (m *ValidatorWeight) Reset()         { *m = ValidatorWeight{} }
func (m *ValidatorWeight) String() string { return proto.CompactTextString(m) }
func (*ValidatorWeight) ProtoMessage()    {}
func (*ValidatorWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_f627751d3cc10225, []int{2}
}
func (m *ValidatorWeight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorWeight.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorWeight.Merge(m, src)
}
func (m *ValidatorWeight) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorWeight.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorWeight proto.InternalMessageInfo

func (m *ValidatorWeight) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryCurrentProviderHoldingPoolRequest)(nil), "interchain_security.ccv.consumer.v1.QueryCurrentProviderHoldingPoolRequest")
	proto.RegisterType((*CurrentProviderHoldingPool)(nil), "interchain_security.ccv.consumer.v1.CurrentProviderHoldingPool")
	proto.RegisterType((*ValidatorWeight)(nil), "interchain_security.ccv.consumer.v1.ValidatorWeight")
}

func init() {
	proto.RegisterFile("interchain_security/ccv/consumer/v1/query.proto", fileDescriptor_f627751d3cc10225)
}

var fileDescriptor_f627751d3cc10225 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x13, 0x08, 0xea, 0x96, 0xf2, 0x61, 0x71, 0x08, 0x11, 0x72, 0x8a, 0x11, 0x55, 0x2e,
	0xdd, 0x25, 0x05, 0x71, 0xe8, 0x05, 0x91, 0x4a, 0xa8, 0x88, 0x4b, 0xb1, 0x10, 0x48, 0x5c, 0xa2,
	0xcd, 0x7a, 0xe5, 0xac, 0xea, 0xec, 0xb8, 0xbb, 0x6b, 0x97, 0x5c, 0xf9, 0x05, 0x48, 0xfc, 0x0b,
	0xfe, 0x04, 0xd7, 0x1e, 0x2b, 0x71, 0x41, 0x1c, 0x02, 0x4a, 0x90, 0x38, 0xc3, 0x2f, 0x40, 0x5e,
	0xdb, 0x54, 0xa5, 0x54, 0xf8, 0x64, 0xfb, 0xed, 0x7b, 0x3b, 0x6f, 0xde, 0x78, 0x10, 0x11, 0xd2,
	0x70, 0xc5, 0x26, 0x54, 0xc8, 0x91, 0xe6, 0x2c, 0x55, 0xc2, 0xcc, 0x08, 0x63, 0x19, 0x61, 0x20,
	0x75, 0x3a, 0xe5, 0x8a, 0x64, 0x03, 0x72, 0x90, 0x72, 0x35, 0xc3, 0x89, 0x02, 0x03, 0xee, 0x9d,
	0x7f, 0x08, 0x30, 0x63, 0x19, 0xae, 0x04, 0x38, 0x1b, 0x74, 0x6f, 0x44, 0x10, 0x81, 0xe5, 0x93,
	0xfc, 0xad, 0x90, 0x76, 0x6f, 0x45, 0x00, 0x51, 0xcc, 0x09, 0x4d, 0x04, 0xa1, 0x52, 0x82, 0xa1,
	0x46, 0x80, 0xd4, 0xe5, 0xa9, 0xc7, 0x40, 0x4f, 0x41, 0x93, 0x31, 0xd5, 0x9c, 0x64, 0x83, 0x31,
	0x37, 0x74, 0x40, 0x18, 0x08, 0x59, 0x9c, 0xfb, 0x7d, 0xb4, 0xf1, 0x3c, 0xf7, 0xb1, 0x93, 0x2a,
	0xc5, 0xa5, 0xd9, 0x53, 0x90, 0x89, 0x90, 0xab, 0x5d, 0x88, 0x43, 0x21, 0xa3, 0x3d, 0x80, 0x38,
	0xe0, 0x07, 0x29, 0xd7, 0xc6, 0xff, 0xd8, 0x44, 0xdd, 0xf3, 0x59, 0x2e, 0x45, 0xd7, 0x33, 0x1a,
	0x8b, 0x90, 0x1a, 0x50, 0xa3, 0x43, 0x2e, 0xa2, 0x89, 0xd1, 0x1d, 0x67, 0xbd, 0xd5, 0x5f, 0xdd,
	0x7a, 0x80, 0x6b, 0x74, 0x87, 0x5f, 0x56, 0xea, 0x57, 0x56, 0x1c, 0x5c, 0xcb, 0x4e, 0x03, 0xda,
	0xbd, 0x8d, 0x2e, 0x6b, 0x43, 0x95, 0x19, 0x4d, 0x2c, 0xd0, 0x69, 0xae, 0x3b, 0xfd, 0x56, 0xb0,
	0x6a, 0xb1, 0x5d, 0x0b, 0xb9, 0x77, 0xd1, 0x15, 0x56, 0x78, 0xac, 0x48, 0x2d, 0x4b, 0x5a, 0x2b,
	0xd1, 0x92, 0x66, 0x50, 0xdb, 0xc0, 0x3e, 0x97, 0xba, 0x73, 0xc1, 0x3a, 0xbc, 0x89, 0x8b, 0x98,
	0x70, 0x1e, 0x13, 0x2e, 0x63, 0xc2, 0x3b, 0x20, 0xe4, 0xf0, 0xf1, 0xd1, 0xbc, 0xd7, 0xf8, 0x35,
	0xef, 0xad, 0xcd, 0xe8, 0x34, 0xde, 0xf6, 0x0b, 0x99, 0xff, 0xe1, 0x6b, 0xaf, 0x1f, 0x09, 0x33,
	0x49, 0xc7, 0x98, 0xc1, 0x94, 0x94, 0x21, 0x17, 0x8f, 0x4d, 0x1d, 0xee, 0x13, 0x33, 0x4b, 0xb8,
	0xb6, 0x37, 0xe8, 0xa0, 0xac, 0xe5, 0x6b, 0x74, 0xf5, 0xaf, 0x26, 0xdd, 0x0e, 0xba, 0x44, 0xc3,
	0x50, 0x71, 0x9d, 0x67, 0xe5, 0xf4, 0x57, 0x82, 0xea, 0xd3, 0x7d, 0x82, 0xda, 0x87, 0x27, 0x6d,
	0xae, 0x0c, 0x71, 0xee, 0xe3, 0xcb, 0xbc, 0xb7, 0x51, 0xa3, 0xec, 0x53, 0x69, 0x82, 0x52, 0xbd,
	0xf5, 0xd3, 0x41, 0x17, 0xed, 0x84, 0xdd, 0x1f, 0x0e, 0xea, 0xfd, 0x67, 0xd6, 0xee, 0xb3, 0x5a,
	0xa3, 0xaa, 0xf7, 0xc7, 0x74, 0x1f, 0xd5, 0xba, 0xec, 0xfc, 0x7b, 0xfc, 0x87, 0x6f, 0x3f, 0x7d,
	0x7f, 0xdf, 0xbc, 0xe7, 0xe2, 0x33, 0xbb, 0x53, 0x0d, 0x39, 0x29, 0x55, 0xa3, 0x49, 0x21, 0x1b,
	0x25, 0x00, 0xf1, 0xf0, 0xc5, 0xd1, 0xc2, 0x73, 0x8e, 0x17, 0x9e, 0xf3, 0x6d, 0xe1, 0x39, 0xef,
	0x96, 0x5e, 0xe3, 0x78, 0xe9, 0x35, 0x3e, 0x2f, 0xbd, 0xc6, 0xeb, 0xed, 0xb3, 0xe9, 0x9d, 0x78,
	0xdc, 0xfc, 0xb3, 0xaa, 0x6f, 0x4e, 0x17, 0xb4, 0xa9, 0x8e, 0xdb, 0x76, 0x63, 0xee, 0xff, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x01, 0x01, 0xe3, 0x8f, 0xdd, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryCurrentProviderHoldingPool(ctx context.Context, in *QueryCurrentProviderHoldingPoolRequest, opts ...grpc.CallOption) (*CurrentProviderHoldingPool, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryCurrentProviderHoldingPool(ctx context.Context, in *QueryCurrentProviderHoldingPoolRequest, opts ...grpc.CallOption) (*CurrentProviderHoldingPool, error) {
	out := new(CurrentProviderHoldingPool)
	err := c.cc.Invoke(ctx, "/interchain_security.ccv.consumer.v1.Query/QueryCurrentProviderHoldingPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryCurrentProviderHoldingPool(context.Context, *QueryCurrentProviderHoldingPoolRequest) (*CurrentProviderHoldingPool, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryCurrentProviderHoldingPool(ctx context.Context, req *QueryCurrentProviderHoldingPoolRequest) (*CurrentProviderHoldingPool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCurrentProviderHoldingPool not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryCurrentProviderHoldingPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentProviderHoldingPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryCurrentProviderHoldingPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.ccv.consumer.v1.Query/QueryCurrentProviderHoldingPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryCurrentProviderHoldingPool(ctx, req.(*QueryCurrentProviderHoldingPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interchain_security.ccv.consumer.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryCurrentProviderHoldingPool",
			Handler:    _Query_QueryCurrentProviderHoldingPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchain_security/ccv/consumer/v1/query.proto",
}

func (m *QueryCurrentProviderHoldingPoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentProviderHoldingPoolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentProviderHoldingPoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *CurrentProviderHoldingPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentProviderHoldingPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentProviderHoldingPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.CurrentHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValidatorWeights) > 0 {
		for iNdEx := len(m.ValidatorWeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorWeights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorWeight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorWeight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorWeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Weight.Size()
		i -= size
		if _, err := m.Weight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCurrentProviderHoldingPoolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *CurrentProviderHoldingPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValidatorWeights) > 0 {
		for _, e := range m.ValidatorWeights {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.StartHeight != 0 {
		n += 1 + sovQuery(uint64(m.StartHeight))
	}
	if m.CurrentHeight != 0 {
		n += 1 + sovQuery(uint64(m.CurrentHeight))
	}
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *ValidatorWeight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Weight.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCurrentProviderHoldingPoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentProviderHoldingPoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentProviderHoldingPoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentProviderHoldingPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentProviderHoldingPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentProviderHoldingPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorWeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorWeights = append(m.ValidatorWeights, &ValidatorWeight{})
			if err := m.ValidatorWeights[len(m.ValidatorWeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentHeight", wireType)
			}
			m.CurrentHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, types.Coin{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorWeight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorWeight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorWeight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Weight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
